---
- hosts: 172.31.15.187,172.31.7.244
  become: true
  tasks: 
    - name: install Docker 
      yum: 
        name: docker
        state: present
    - name: start and enable docker 
      service:
        name: docker
        state: started
        enabled: true


